### ISSUE TITLE
Current Status?

### ISSUE THREAD

**Issue by darrencruse** [dzek69/react-native-indoor-atlas#1]
Hi just stumbled on your package wondering if there were already RN bridges for indoor atlas happy to see your project!!

I see the android directory but no Swift yet right?

Is adding Swift a part of your plans?

And for the android support I see here would you call it "production worthy"? :)

Thanks,

Darren Cruse

**Comment by dzek69** [comment]
Hello.

There is another package `react-native-indoor-manager` that was created before this one, but
- it is troublesome to install on current React Native projects
- it uses outdated Indoor Atlas SDK
- had memory leaks IIRC
- was covering only very basic use cases (this one isn't feature complete too)
- it looks abandoned

This is why I've created this one and was planning to make it full featured package.
It should be production-ready and IIRC it covers all features of `react-native-indoor-manager`

But I stopped using Indoor Atlas technology at all and therefore stopped development of this library. Why?

Indor Atlas is way too inaccurate. It's less accurate than I could calculate myself, while it promised otherwise. Won't tell more in public to avoid lawsuits or something, but you can catch me via e-mail (see my commits), Skype or Telegram (same ID as on Github) and I'll tell you about my/our experiences. We invested way too much time on it and I'd not use it if I knew what I know now before we started the project.

So: there are no plans for Swift/iOS part right now.

If you however decide to keep using Indoor Atlas and this library and want to upgrade it - we can talk more on this. I've caught nice `react-native-indoor-atlas` name on npm and would be happy to see it living after I've started it.

**Comment by darrencruse** [comment]
Thanks for the info (about your package and yeah I was also looking at react-native-indoor-manager so thanks for your comments about that one too).

Sorry to hear about the accuracy problems you had with Indoor Atlas.  I'm new to Indoor Atlas I was helping out some coworkers who'd already chosen it.

(maybe I will email you I'm most curious to ask did you talk to the Indoor Atlas people about your issues did they have any suggestions?)

**Comment by dzek69** [comment]
IA support was pretty slow to response, but at least was responding.
After I told them I stopped using their services because of bad accuracy and my findings how it really works internally and how their promo vides are probably faked - they haven't replied anymore.

Catch me via e-mail and I may save you some trouble

**Comment by gvmarvelos** [comment]
Good night what is the current state? Did you comment on the inaccuracy of the IA, could you please give us any suggestions?
