### ISSUE TITLE
Current state? Or suggestion.

### ISSUE THREAD

**Issue by gvmarvelos** [dzek69/react-native-indoor-atlas#2]
Good night what is the current state? Did you comment on the inaccuracy of the IA, could you please give us any suggestions?

**Comment by dzek69** [comment]
Hello,

The project is dead from my side, but I will accept PRs if any. If you want to take over the whole project I may think about it too.

My suggestion would be to switch to test with current version if IA suits you (they could get better since I've tested it) and if not - look for another solution.
If it suits you I can recommend trying to upgrade this library, it's pretty clear to follow IA docs and current code and contribute to what I've started.

I think I will update README with current status soon.

**Comment by gvmarvelos** [comment]
Thank you very much for your quick response.

The project is still in its infancy so I will try to use what you have already created to see if it is enough for my project.

Could you tell me what level of precision the AI ​​allows?

How long ago did you take your last AI test?

Is it too complex to continue with what you've already done?

Finally, would you have any suggestions for another service, like AI in case I were to replace?

I'm sorry for the amount of questions, but it's because you apparently have a lot of experience and I need this help.

Thank you!

**Comment by dzek69** [comment]
> Could you tell me what level of precision the AI ​​allows?

I can't really respond to that, because that depends on your environment (wifi networks, bluetooth beacons), but for me worst case was around 50m (while walking) and the best was around 5m (after stopping for about 20 seconds).

> How long ago did you take your last AI test?

12 months ago.

> Is it too complex to continue with what you've already done?

Shouldn't be. I usually care about code quality, including readability. Feel free to ask some questions if needed.

> any suggestions for another service, like AI

Not really. Estimote seems promising, but I have not tested their location services (but I have few of their beacons). For my needs I just used bare bluetooth beacons with low transmit power and manually tried to calculate position based on visibility and signal strength. It was good enough, but the whole project eventually went dead anyway.

> I'm sorry for the amount of questions

No problem, I've spent years helping other people on the internet in the past and I still enjoy it :) Currently my time is very limited, but I try to keep maintenancing what I've published (like fixing security warnings, in this repo - 5 months ago) and responding to messages.

**Comment by gvmarvelos** [comment]
These answers helped me a lot!

You used a good strategy to solve it! I believe that 10 meters walking would be comfortable for me. But I'll give it a try!

Thanks again for the availability. And any questions I come to ask you again! Thank you!
